[PHP]
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 50M

date.timezone = Europe/Warsaw

opcache.enable = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
opcache.fast_shutdown = 1

realpath_cache_size = 4096K
realpath_cache_ttl = 600

display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED

expose_php = Off

[pcov]
pcov.enabled = 1
pcov.directory = /var/www/html/src
