[PHP]
memory_limit = 256M
upload_max_filesize = 50M
post_max_size = 50M

date.timezone = Europe/Warsaw

opcache.enable = 1
opcache.memory_consumption = 128

display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED

expose_php = Off

[pcov]
pcov.enabled = 1
pcov.directory = /var/www/html/src
